package tryCatch;

import Exceptions.MathOperations;

public class TestRun {

	public static void main(String[] args) {
		MathOperations matop= new MathOperations();
		matop.addThreeNumbers(45, 10, 20);

	}

}
